# Generated by Django 6.1 on 2026-08-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("period_config", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("timezone", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("sunrise", "Sunrise"),
                            ("sunset", "Sunset"),
                            ("fixed_time", "Fixed local time"),
                        ],
                        default="sunrise",
                        max_length=20,
                    ),
                ),
                (
                    "delay_hours",
                    models.FloatField(
                        default=3.0,
                        help_text="Offset after the trigger event; ignored for fixed_time",
                    ),
                ),
                (
                    "trigger_time",
                    models.TimeField(
                        blank=True,
                        help_text="Local time of day to trigger; used only when trigger_type is fixed_time",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "step_class",
                    models.CharField(
                        help_text="Dotted path, e.g. pyobs.images.processors.misc.Calibration",
                        max_length=255,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="reduction.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReductionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("logs", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="reduction.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SitePipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("local", "Local directory"),
                            ("archive", "PyobsArchive"),
                        ],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("input_config", models.JSONField(blank=True, default=dict)),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("local", "Local directory"),
                            ("archive", "PyobsArchive"),
                        ],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("output_config", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_assignments",
                        to="reduction.pipeline",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_assignment",
                        to="reduction.site",
                    ),
                ),
            ],
        ),
    ]
