# Generated by Django 6.1 on 2026-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="siteid",
            field=models.CharField(
                blank=True,
                help_text='Site code as known to the archive (e.g. "monets"), used when querying frames. Not necessarily the same as the display name above -- falls back to it if left blank.',
                max_length=100,
            ),
        ),
    ]
