# Generated by Django 6.1 on 2026-08-10 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduction", "0002_site_siteid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Site name can't contain \"/\" -- it's used directly in URLs.",
                        regex="^[^/]+$",
                    )
                ],
            ),
        ),
    ]
