# Generated by Django 6.1 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduction", "0003_alter_site_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reductionperiod",
            name="progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
