# Generated by Django 6.1 on 2026-09-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reduction", "0004_reductionperiod_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reductionperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("COMPLETED_WITH_ERRORS", "Completed with errors"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=22,
            ),
        ),
    ]
